import sys
import os, time
import urllib # this library is used to open url links 
import cognitive_face as CF
import urllib
import sqlite3
from global_variables import personGroupId   # 'mygroup'


Base_url = 'https://westcentralus.api.cognitive.microsoft.com/face/v1.0' # default endpoint when use free 
CF.BaseUrl.set(Base_url)
Key= '20c5c11712244ba4b340ac8bf949b8ef' # subscription key needed 
CF.Key.set(Key)

def get_person_id():
    person_id = ''
    extractId = str(sys.argv[1])[-2:]
    connect = sqlite3.connect("face-database.db")
    c = connect.cursor()
    cmd="select * from students where ID = "+extractId 
    c.execute(cmd)
    row = c.fetchone() # this will return a tuple - the whole row from the table where id extracted from the sysargv
    #print(type(row))
    person_id = row[3]
    connect.close()
    return person_id # returning the personId (generated by MCS Azure)

if len(sys.argv) is not 1:  # input should be like this - python3 add_person_faces.py user79
    #print(os.path.abspath(__file__)) - return the absolute path from the begining 
    currentDir = os.path.dirname(os.path.abspath(__file__))
    #print(currentDir)
    imageFolder = os.path.join(currentDir,"database/"+str(sys.argv[1]))
    person_id = get_person_id()
    #print(os.listdir(imageFolder)) - this will provide you the list containing all the images present at that address 
    for filename in os.listdir(imageFolder) : # going through each and every images present in the database folder 
         if filename.endswith(".jpg"):
         	 #print(filename)
             #print(os.path.join(imageFolder,filename)) - /Users/adityaatri/Desktop/Projects/attendance_system/database/user79/User.79_12.jpg
             imgurl = urllib.request.pathname2url(os.path.join(imageFolder,filename))
             res = CF.face.detect(imgurl)
             if len(res)!=1:
             	print("No face detected in image")
             else :
             	res = CF.person.add_face(imgurl,personGroupId,person_id) #adding the face corresponding to given person_id 
             	print(res)
             time.sleep(6)

















 


